version: '3'
services:

  database:
    image: postgres
    container_name: astronauta-database
    build: .docker/postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=astronauta
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    restart: always
    container_name: astronauta-app
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local